### ISSUE TITLE
Grass Clipper 압축해제 후 실행파일 실행이 안됩니다.

### ISSUE THREAD

**Issue by XroXng** [tsukiroku/grasscutter-guide#1]
GrassClipper.exe를 실행하면 하얀 창이 나오는데 그 후로 바로 종료됩니다.

**Comment by yulmwu** [comment]
https://github.com/Grasscutters/GrassClipper/issues/64 참고 해보시기 바랍니다.
`GrassClipper` 가 `OneDrive` 경로에 존재한다면, 위와 같은 오류가 발생할 수 있다고 합니다.

**Comment by XroXng** [comment]
Onedrive를 제거를 해도 그러네요. 브라우저를 통해 실행해도 안되고요. *수정 파일을 다른 드라이브로 옮기니 해결 됐습니다. 도움 주셔서 감사해요!
