### ISSUE TITLE
며칠전까지 이용하다가 4214오류가뜹니다

### ISSUE THREAD

**Issue by giteriri** [tsukiroku/grasscutter-guide#2]
7월 9일 설치해서 13일까지 이용했습니다.
지금 접속하니 4214오류가 뜨는데 따로 업데이트해야하는게 있나요?

**Comment by yulmwu** [comment]
* grasscutter 데이터 업데이트

* **2.8 이상부터 `global-metadata.dat`가 grasscutter가 호환되지 않는 것으로 확인됩니다.**

>  [해당 (클릭)](https://drive.google.com/file/d/1Im1CQH1bF1fi7oiiyjNWBul6MgOXbHOt/view) 파일을 `Genshin Impact game\GenshinImpact_Data\Managed\Metadata` 위치에 복사 & 붙여 넣기 후, 해당 파일을 `global-metadata.dat`로 변경한 다음[₁](#1), grasscutter를 실행하면 (grassclipper) 정상적으로 로그인 될 겁니다.
> 
> > [₁](#1) **기존의 `global-metadata.dat`는 반드시 백업을 해둘 것.**

**그럼에도 로그인 되지 않는다면, [grasscutter 공식 디스코드](https://discord.gg/grasscutter)에 문의 해보시기 바랍니다.**

**위 경우로 성공 시, 2.7로 이용이 가능하며, 사설 서버가 아니라면, 기존 파일로 교체해야 합니다.**
