### ISSUE TITLE
혹시 이거 인게임에서 캐릭터들 음성나오나요??

### ISSUE THREAD

**Issue by Minerval13** [tsukiroku/grasscutter-guide#3]
다른방법으로 구축했는데 안나와서....

혹시 이방법으로하면 캐릭터들 음성나오나요??

**Comment by yulmwu** [comment]
다른 방법으로 구축 후, 인게임 캐릭터 음성이 안나오는 경우는 [데이터](https://github.com/Dimbreath/GenshinData) 문제일 확율이 높습니다.

위 파일 업데이트 후, 그래도 안되면 사설 서버 없이 인게임에서 캐릭터 음성이 들리는지 확인해보시고, 음성이 안 들린다면 게임 재설치(복구), 사설 서버가 아닌 클라이언트에서만 음성이 들린다면 **해당 사설 서버를 다시 설치 해보시거나, grasscutter (해당 레포) 사설 서버를 시도해보시기 바랍니다.**

**Comment by Minerval13** [comment]
제가 지금 3.0베타로 구축을했는데 혹시다르게해야하나요...?

**Comment by Minerval13** [comment]
> 제가 지금 3.0베타로 구축을했는데 혹시다르게해야하나요...?
https://arca.live/b/dev0/55028805 <<여기 방법대로했는데 다른방식이라서 적용이안되는걸까요...

**Comment by yulmwu** [comment]
위 글에서 [공유된 클라이언트](https://autopatchhkbeta.yuanshen.com/client_app/download/beta_pc/20220708104232_lwGnJdsYwFVCZDTT/GenshinImpact_2.8.50_beta.zip) 문제인 듯 합니다.

해당 클라이언트에서 사운드 관련 설정과, 운영체제 사운드 관련 설정을 해보시길 바랍니다.

(2.8 클라이언트는 3.0 grasscutter를 실행할 수 없음)

또한 위 글에서 공유된 3.0 리소스 레파지토리를 확인해본 결과, 저작권 문제로 조치되어, 사용할 수 없는 것으로 보입니다.

3.x 버전은 확인하지 않아, 자세하게 못 도와드린다는 점 이해해주시면 감사하겠습니다.

위 아카라이브 글 댓글로 문의하여 해결 방안을 찾거나, 3.0 클라이언트와 grasscutter가 나올 때 까지 기다리는 것도 하나의 방법입니다.
